### ISSUE TITLE
How to check a variable if defined?

### ISSUE THREAD

**Issue by SakuraZhang** [phalcon/zephir#1026]
In the project ,there need to check the variable if defined .When I try to translate the php to zephir,I can't fand a way to process it,is there a good way to deal with id ?Thank you.
```php
namespace Test
if(!defined("REGREXP_ERROR")){
    defined('REGREXP_ERROR' ,0);
}
class Calculate{
    const CALCULATE_REGREXP_ERR = REGREXP_ERROR;
}
```

**Comment by steffengy** [comment]
You cannot execute code without a method/function.
If you just want to ensure that this constant is being initialized, you could do this by using a
custom initializer function (requires C).
The (probably) more maintainable solution would be to
implement this using class constants,
for example with a parent class of Calculate.

**Comment by SakuraZhang** [comment]
That is to say unless the C code I can't validate it in zephir code by PHP style?

**Comment by steffengy** [comment]
If you had that like that in PHP it would be executed when the file is required,
which isn't possible in zephir, since the classes are all registered at the same time.

A solution could be
a) define some kind of an init method/function, which you simply call at startup 
b) move the constant to a parent class (which probably is anyways the cleaner solution)

That's atleast anything I could think of at the moment.

**Comment by SakuraZhang** [comment]
Thanks a lot,I will try your solution.
