### ISSUE TITLE
Use phalcon from zephir module

### ISSUE THREAD

**Issue by DaveM2011** [phalcon/zephir#304]
As the title states how can i use phalcon from within my own zephir module

```
namespace Rapid\Models;
class Users extends \Phalcon\Mvc\Model
{
}
```

Thanks Dave

**Comment by DaveM2011** [comment]
I did make a little progress making it read the model class but then it fails with 

```
Zephir\CompilerException: Method 'Rapid\Model\Tokens::belongsTo' called with a w
rong number of parameters, the method has: 0, passed: 4 in /root/rapid/rapid/mod
el/tokens.zep on line 29

this->belongsTo("user_id", "\\Rapid\\Model\\Users", "id", ["alias": "User", "foreignKey": true]);
-----------------------------------------------------------------------------------------------^

```

MethodCall.php Line: 209

I have no idea how to fix it ive tried adding headers, adjusting the bottom of ClassDefinition.php adding

```
case 'phalcon\mvc\model':
                $compilationContext->headersManager->add('ext/phalcon/phalcon/mvc/model');
                $classEntry = 'phalcon_mvc_model_ce';
                break;
```

Still no luck :(

**Comment by DaveM2011** [comment]
OMG thats great i will try your fix shortly i have to take a look at other software most of today but should be able to test it later on and ill let you know :)

> For every phalcon class you want to extend you will have to find it's header file and add PHPAPI right after extern and before zend_class_entry

i wondered why PHPAPI was not in the header files i thought maybe zephir added it elsewhere :)

**Comment by OpenEX** [comment]
Based on what has been already said here, i've been thinking about making my Zephir AaaaaaController class visible from PHP with Phalcon on board. All compiles great (installed/ini/extension order), but the class is not visible when i write http://domainwiththeapp/aaaaaa  . What i wouldn't like to do is to create a class in PHP extending my AaaaaaController class - this i did with success. . I guess the problem is with namespace. Is there a way to make this class visible for this address and for phalcon. Any suggestions would be appreciated.

**Comment by vexor-dev** [comment]
<code>zephir build --export-classes</code>

don't work to compile phalcon anymore (testet with branches 2.0.0, 2.0.x and 2.1.x and Zephir 0.7.1b) . Compilation stops with:

<code>Zephir\CompilerException: updateArray: variable</code>

Is there a equivalent for  --export-classes  in:
<code>
cd cphalcon/build
</code>
<code>
./install
</code>

**Comment by steffengy** [comment]
That is a general issue regarding phalcon and the development branch,
since the refactoring process is not complete and 
therefore not all functionality is yet supported again.

That specific error `Zephir\CompilerException: updateArray: variable`
above should now be fixed.

**Comment by vexor-dev** [comment]
Thanks. Your right, exception has gone for another one

<code>PHP Catchable fatal error:  Object of class Zephir\CompiledExpression could not be converted to string in /opt/zephir/Library/SymbolTable.php on line 207</code>

caused by Phalcon\Di\Service  in line 238

<code>let arguments = [position: parameter];</code>

If i change this the compiler throws

<code>Compiling...</code>
<code>Installing...</code>
<code>Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information</code>

compile-errors.log:
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c: In function 'zim_Phalcon_Db_Dialect_getSqlColumn':</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:402:61: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:410:60: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c: In function 'zim_Phalcon_Db_Dialect_getSqlTable':</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:624:53: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:626:52: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c: In function 'zim_Phalcon_Db_Dialect_getSqlExpressionList':</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:1198:58: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c: In function 'zim_Phalcon_Db_Dialect_getSqlExpressionOrderBy':</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:1710:53: error: expected expression before ',' token</code>
<code>make: **\* [phalcon/db/dialect.lo] Error 1</code>
<code>make: **\* Waiting for unfinished jobs....</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c: In function 'zim_Phalcon_Db_Dialect_getSqlColumn':</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:402:61: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:410:60: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c: In function 'zim_Phalcon_Db_Dialect_getSqlTable':</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:624:53: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:626:52: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c: In function 'zim_Phalcon_Db_Dialect_getSqlExpressionList':</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:1198:58: error: expected expression before ',' token</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c: In function 'zim_Phalcon_Db_Dialect_getSqlExpressionOrderBy':</code>
<code>/opt/cphalcon/ext/phalcon/db/dialect.zep.c:1710:53: error: expected expression before ',' token</code>
<code>make: **\* [phalcon/db/dialect.lo] Error 1</code>

Testet with Zephir version 0.7.1b and Phalcon 2.1.x

**Comment by vexor-dev** [comment]
Compiling own extensions with Zephir (>= 7) which extends other libraries like Phalcon (only from source) fails.

First example:
Phalcon 2.1.0b
Zephir Version 0.9.1a-dev

Utils 0.0.1
Zephir Version 0.9.1a-dev

utils config.json

```
...

    "external-dependencies": {
        "phalcon": "/opt/cphalcon"
    }

...
```

utils/utils/greeting.zep

```
class Greeting extends \Phalcon\Mvc\User\Component {

    protected function getFoo() {
        return this->getDi()->getShared("foo");
    }

}
```

Error

```
/usr/bin/php5 -dextension="/opt/zephir/Library/../parser/zephir_parser.so" /opt/zephir/compiler.php build --parser-compiledZephir\CompilerException: Class 'Utils\Greeting' does not implement method: 'getDi' in /opt/utils/utils/Greeting.zep on line 11

      return this->getDi()->getShared("foo");
```

Second example:
Phalcon 2.1.0b
Zephir Version 0.9.1a-dev

Utils 0.0.1
Zephir Version 0.6.1a

<code>
Warning: Class "Utils\DiInterface" does not exist at compile time in /opt/utils/utils/Greeting.zep on 11 [nonexistent-class]

```
  return this->getDi()->getShared("foo");
----------------------------------------^
```

Copying new kernel files...

Preparing for PHP compilation...

Preparing configuration file...

Compiling...

Installing...

Extension installed!

Add extension=utils.so to your php.ini

Don't forget to restart your web server

</code>

Code is exact the same as in the first example and it works. Testet with Debian and compiled phalcon with "zephir build --export-classes"
