### ISSUE TITLE
Avoid tmp variables duplication

### ISSUE THREAD

**Issue by ovr** [phalcon/zephir#561]
Suggestion

Pass tmp names
- Use `thisPropertyTmp1` instead of `_0`
- Try to find variable in `ConditionBase` or `Expression` 'property-access' case and setExpectedReturn to PropertyAccess Expression

Proof https://github.com/phalcon/zephir/pull/560
##

**Comment by steffengy** [comment]
@ovr 
Since I think this is something quite important, is there any update on this?

Besides the variable duplication, one should also take a look at code duplication
within zephir generally. This makes updating to PHP7 increasingly more difficult.
(Kernel and Compiler wise there are many code duplications, leading to **worse maintainability**, 
requiring bugs to be fixed at several places, ...)
