### ISSUE TITLE
Incorrect array element fetching on var assignment

### ISSUE THREAD

**Issue by SliceOfLife** [phalcon/zephir#709]
I have a simple code:

```zep

	public static function doSomething()
	{
		var arr;

		let arr = [1, 2];
		let arr = arr[array_rand(arr)];

		echo arr, "\n";
	}

```
But it produce incorrect output. I ran it several times and got this:
```
4478337920
4513325952
2
4422243200
4441392000
4582888320
2
2
4422804352
4594230144
2
2
4509430656
...
```

If I create an additional variable like that:

```zep
	public static function doSomething()
	{
		var arr, arrElem;

		let arr = [1, 2];
		let arrElem = arr[array_rand(arr)];

		echo arrElem, "\n";
	}
```

all works fine.

Zephir version 0.5.9a

**Comment by steffengy** [comment]
Just tried that and
the problem here is that in that specific case the following happens:
- Pointer to arrElem is taken
- arr is set to Pointer from above
- old arr stuff gets freed -> that random data

No copy is used in that case: Currently no real idea how to fix that properly
You could use that workaround.
Better would probably be to enable copy in that specifc scenarios?
Again something to leave for somebody who knows the internals...
@phalcon @andresgutierrez
